#!/usr/bin/expect -f
set timeout -1
spawn ssh -o StrictHostKeyChecking=no root@54.255.186.244
expect {
  "password:" {
    send "NerssBiU56\r"
    exp_continue
  }
  "#" {
    send "curl -vs -X POST http://localhost:8081/api/v1/auth/login -H 'Content-Type: application/json' -d '{\"loginId\": \"admin\", \"password\": \"admin123\"}' > /root/curl_login.log 2>&1 && cat /root/curl_login.log\r"
  }
}
expect "#"
send "exit\r"
expect eof
