#!/usr/bin/expect -f
set timeout 10
spawn ssh -o StrictHostKeyChecking=no root@54.255.186.244
expect "password:"
send "NerssBiU56\r"
expect "#"
send "docker logs --tail 200 project-manage-backend > /root/backend_logs.txt\r"
expect "#"
send "exit\r"
expect eof

spawn scp -o StrictHostKeyChecking=no root@54.255.186.244:/root/backend_logs.txt ./backend_logs.txt
expect "password:"
send "NerssBiU56\r"
expect eof
